### ISSUE TITLE
package.json and package-lock.json believe this action is named "typescript-action"

### ISSUE THREAD

**Issue by JasonGross** [avsm/setup-ocaml#17]
https://github.com/avsm/setup-ocaml/blob/2616b4901a114ff3dc525e23322a9187022e3086/package-lock.json#L2-L3
https://github.com/avsm/setup-ocaml/blob/2616b4901a114ff3dc525e23322a9187022e3086/package.json#L2-L3
Hence if I do
```
$ npm install avsm/setup-ocaml
```
I get
```
└── typescript-action@0.0.0  extraneous (git://github.com/avsm/setup-ocaml.git#2616b4901a114ff3dc525e23322a9187022e3086)
```

**Comment by imbsky** [comment]
Why do you need to install this action using npm?

**Comment by JasonGross** [comment]
I was trying to build an action to setup Coq on top of this action

**Comment by imbsky** [comment]
If so, I don't recommend installing this action as an npm package.

**Comment by imbsky** [comment]
I'm also interested in and learning about Coq, so I can help you create that action if necessary.

**Comment by giltho** [comment]
I don't think there is an elegant way of composing actions just yet (except inside a workflow).
What else does your action needs to do appart from `opam install coq` after setting up ocaml ?

**Comment by JasonGross** [comment]
@imbsky having your help would be great!

@giltho Not much, just to the relevant `opam repo add` if the user asks for the dev version of Coq, and also to add [this problem matcher](https://github.com/mit-plv/fiat-crypto/blob/master/.github/coq.json) so warnings and errors get annotated.  (The [installation instructions](https://coq.inria.fr/opam-using.html) claim I also need to `sudo apt-get install m4` if it's not already installed.). (I also might want to use pre-built binaries for Coq and OCaml someday, but that's for another day.)

**Comment by avsm** [comment]
That's simple enough that I'm happy to add that to this action, if you'd like.   We could just add a yaml key along the lines of "install: coq".

**Comment by JasonGross** [comment]
@avsm That'd be great, thanks!  (I think most versions of coq don't need any special opam repo, but any versions ending in `dev` or `beta`*n* for any *n* need to add https://github.com/coq/opam-coq-archive/tree/master/core-dev/packages/coq)

**Comment by imbsky** [comment]
I'm working on speeding up this action, so once it's done, this allows set up the OCaml/opam environment very quickly and install coq without stress.

**Comment by imbsky** [comment]
If you want to add some special support for coq, open another issue. This issue will be closed once.

**Comment by smorimoto** [comment]
@JasonGross I've started a project to ensure that the deploy the pre-built OCaml compiler binary cache into the environment, and it's almost done. Will such a project be useful in the Coq community? It seems that the Coq community is developing their own action, so I was wondering. If you need any help, I can help.

**Comment by JasonGross** [comment]
Thanks for the offer, but as I understand it, the Coq community is set with the docker-based solution.  We might someday try to get a non-docker-based action, and this might be helpful then

**Comment by smorimoto** [comment]
Oh, I see!
