### ISSUE TITLE
Adding specific cygwin packages?

### ISSUE THREAD

**Issue by rivy** [avsm/setup-ocaml#38]
I'm trying to construct a GHA workflow to automatically construct the windows [`unison`](https://github.com/bcpierce00/unison) artifact from a [suggested recipe](https://github.com/bcpierce00/unison/pull/330/files). To do so, I need to add some cygwin packages... how would that be done?

My initial thought was to use the cygwin setup executable, but I'm not sure where it is.

Thanks for the work creating this action and, in advance, for the help here!

**Comment by smorimoto** [comment]
Adding a Cygwin package after setup with the action is a bit of a pain. There are currently two things we can do: make some changes to the action or provide you with YAML code for GitHub Actions for Windows that doesn't use the action.

Well, here's the setup stuff for Cygwin.
https://github.com/avsm/setup-ocaml/blob/master/src/install-ocaml-windows.cmd

By the way, opam 2.2 will include native Windows support, So I didn't intend to make a major change to the action.

**Comment by rivy** [comment]
> Adding a Cygwin package after setup with the action is a bit of a pain. There are currently two things we can do: make some changes to the action or provide you with YAML code for GitHub Actions for Windows that doesn't use the action.
> 
> Well, here's the setup stuff for Cygwin.
> https://github.com/avsm/setup-ocaml/blob/master/src/install-ocaml-windows.cmd

I'm not sure the best way to proceed. [The recipe](https://github.com/bcpierce00/unison/pull/330/files) suggests 32-bit Cygwin as well as installation of the "mingw64-i686-glib2", "mingw64-i686-gtk2", and "mingw64-i686-pango" packages. I'm not sure of the size or installation time of those packages, but I'd hate to add their weight for all users. I'm not even sure it'll work under a 64-bit Cygwin installation, but I wanted to make some first steps.

I was thinking about a parameter for extra cygwin packages ("add_cygwin_packages"). Or, maybe even simpler, just copy the setup to a known location (eg, `copy %2/setup-x86_64.exe %CYWIN_ROOT%\bin`) which could then be used in a later setup step (eg, `c:\cygwin\bin\setup_x86_64.exe --quiet-mode --root %CYGWIN_ROOT% --site http://cygwin.mirror.constant.com --packages mingw64-i686-glib2,mingw64-i686-gtk2,mingw64-i686-pango`). The copy method would only entail one extra line in the `install-ocaml-windows.cmd` file.
 
> By the way, opam 2.2 will include native Windows support, So I didn't intend to make a major change to the action.

Will that be helpful? I have doubts that installing glib, gtk, pango, and labgtk2 will be easy (or even possible) in a non-POSIX (ie, Cygwin) environment.

And thanks for the attention.

**Comment by smorimoto** [comment]
It's technically possible, but it conflicts with our philosophy. https://github.com/avsm/setup-ocaml#roadmap

If you build on native Windows (It means not to use Cygwin), you can use MSYS2. It's not as complex as Cygwin.

**Comment by rivy** [comment]
> It's technically possible, but it conflicts with our philosophy. https://github.com/avsm/setup-ocaml#roadmap (Overall, I'm not trying to argue against your thought.)

How about the "copy" alternative?
It's a simple change that doesn't add any real complexity or features. I can create a quick PR for it in a few minutes.
 
> If you build on native Windows (It means not to use Cygwin), you can use MSYS2. It's not as complex as Cygwin.

I've not seen any way to build `unison` with a GUI via MSYS, nor even how to install OCaml within or using that system.

**Comment by smorimoto** [comment]
Hmm, what does "copy" mean? that's not a goal we should aim for.

I'm not sure because I've never done that either.

Another option seems to be to use `apt-cyg`, but I've never used it.

**Comment by rivy** [comment]
> Hmm, what does "copy" mean? that's not a goal we should aim for.

>> Or, maybe even simpler, just copy the setup to a known location (eg, `copy %2/setup-x86_64.exe %CYWIN_ROOT%\bin`) which could then be used in a later setup step (eg, `c:\cygwin\bin\setup_x86_64.exe --quiet-mode --root %CYGWIN_ROOT% --site http://cygwin.mirror.constant.com --packages mingw64-i686-glib2,mingw64-i686-gtk2,mingw64-i686-pango`). The copy method would only entail one extra line in the `install-ocaml-windows.cmd` file.

This shouldn't conflict with any of the stated goals of the project. It's just putting the setup program into a known, usable location.

I created a very small PR (#39) that implements the copy.

**Comment by dra27** [comment]
A few flyby observations:

- Running Cygwin setup twice in the same run is very inefficient - it would be far better to allow `%3` for `install-ocaml-windows.cmd` to be a list of additional packages to install and thread that back to the workflow as an input variable
- In terms of being platform-neutral, specifying additional Cygwin packages would be like specifying additional apt or brew packages to be installed - so you could have an `extra_os_packages` field which is interpreted by all the platforms and leave it to the workflow author to ensure that their matrix specifies the correct names for each different os.
- The opam way would be to do this with depexts (which would require no alteration to setup-ocaml)

**Comment by rivy** [comment]
I'm open to however you want to try this... My ultimate goal is to have an automatic build/compilation of a graphic GUI windows version of `unison`. Given that's been a very hard target, it's going to take some iteration of tools and recipe, if it's even really possible. 🤞

**Comment by dra27** [comment]
> I'm open to however you want to try this... My ultimate goal is to have an automatic build/compilation of a graphic GUI windows version of `unison`. Given that's been a very hard target, it's going to take some iteration of tools and recipe, if it's even really possible. 🤞

I certainly managed to build the GUI in mid-2018 with mingw-w64 OCaml 4.06. IIRC most of the problems were to do with lablgtk needing updates, and the fact that it required a manually patched flexdll (the patch was always included in fdopen's opam fork and the recently released FlexDLL 0.38 includes that fix).

**Comment by rivy** [comment]
> I certainly managed to build the GUI in mid-2018 with mingw-w64 OCaml 4.06. IIRC most of the problems were to do with lablgtk needing updates, and the fact that it required a manually patched flexdll (the patch was always included in fdopen's opam fork and the recently released FlexDLL 0.38 includes that fix).

I'd love to know the process.

With a fresh current installation of MSYS2, I'm unable to even install OCaml.
`pacman -Sy mingw-w64-ocaml` returns a "no package found" error.

**Comment by dra27** [comment]
> > I certainly managed to build the GUI in mid-2018 with mingw-w64 OCaml 4.06. IIRC most of the problems were to do with lablgtk needing updates, and the fact that it required a manually patched flexdll (the patch was always included in fdopen's opam fork and the recently released FlexDLL 0.38 includes that fix).
> 
> I'd love to know the process.
> 
> With a fresh current installation of MSYS2, I'm unable to even install OCaml.
> `pacman -Sy mingw-w64-ocaml` returns a "no package found" error.

See [ocaml.org instructions](https://ocaml.org/docs/install.html#Windows), and also [OCaml's installation instructions](https://github.com/ocaml/ocaml/blob/trunk/README.win32.adoc) - MSYS2 is not supported.

**Comment by rivy** [comment]
I've got a Cygwin installation and have worked through one full construction to the UI version with the 'OCaml 32-bit' version. I didn't use any patches. But, so far, I'm still struggling to construct a static version or to get the 'OCaml 64-bit' version built. I believe that you're using the OCaml 64-bit version here. So, to get a GHA auto-build working, I still need to get a construction under that 64-bit version working. Any insights you have would be welcome.
