### ISSUE TITLE
Reduce setup time

### ISSUE THREAD

**Issue by shonfeder** [avsm/setup-ocaml#44]
This is a super helpful utility to have in the ecosystem. However, I notice that setup actions for other languages such as Java and Rust are several orders of magnitude faster (they are in the order of seconds, while we are often pushing 10 minutes or so).

I wonder if there is anything essential about the way opam is distributed that prevents us being able to match those speeds, or if we just need to study their actions from clever tricks.

**Comment by dra27** [comment]
This is basically #1 or the lack of a shared binary artefact cache for OCaml. Without caching, virtually all pipelines are init'ing opam, building a compiler and compiling Dune (and probably a lot of other dependencies). Caching is hard (and already tracked in #1), shared binary artefact caches are extremely hard, but being worked on. Using a Docker image is tricky (if not impossible) owing to depexts, IIRC. A possibility might to have an opam-repository with binary versions of the compiler for the specific macOS and Ubuntu workers used in the pipelines (which is how the Windows opam-repository works), but maintaining that adds _considerable_ burden.

It's of course fine to have discussion about specific possible improvements, but I'm not sure having a "Just make it faster" issue is good for morale 🙂

**Comment by shonfeder** [comment]
Thanks, @dra27. I definitely don't want to contribute to lowered moral! I think I must have misunderstood #1, which I took to be about caching built opam packages, not for caching the dependencies of the action itself (including the opam binary). But now that you've explained. I'll close this, leaving it up to you all to reopen if you decide it is relevant. :)
