### ISSUE TITLE
set-env and add-path are deprecated warnings

### ISSUE THREAD

**Issue by anton-trunov** [avsm/setup-ocaml#46]
This is something I started getting from GitHub Actions recently:
```
Run avsm/setup-ocaml@v1
  with:
    ocaml-version: 4.09.1

Warning: The `set-env` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Warning: The `add-path` command is deprecated and will be disabled soon.
Please upgrade to using Environment Files.
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by smorimoto** [comment]
Yeah, I know that. It has already been fixed in master, so I will make a new release today or tomorrow. Well, I know because I'm one of those people who are deeply involved in the actions ecosystem, but that's not going to be an immediate problem.

**Comment by smorimoto** [comment]
Already fixed in the latest master.

**Comment by anton-trunov** [comment]
Thank you so much @smorimoto! I look forward to the new release.

**Comment by smorimoto** [comment]
The release was released a long time ago, so as long as you're using `v1`, there's no problem.
