### ISSUE TITLE
`dune: command not found` in runsvc.sh mode

### ISSUE THREAD

**Issue by pivdets** [avsm/setup-ocaml#47]
I ran the self-hosted github action as [issues-42](https://github.com/avsm/setup-ocaml/issues/42) mentioned.

I found that it works well in the front end terminal, but if I make it as a backend service by running `./svc.sh start` ([refer](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service)), and if failed with log

```shell
Run dune external-lib-deps --missing @@default
/home/piv/actions-runner/_work/_temp/03de7349-c990-4f01-bfb7-2c712b5b273d.sh: line 1: dune: command not found
Error: Process completed with exit code 127.
```

**Comment by pivdets** [comment]
Fixed it by adding `/home/piv/.opam/default/bin:` into **actions-runner/.path**

**Comment by smorimoto** [comment]
Just do the following:
`opam exec -- dune external-lib-deps --missing @@default`
