### ISSUE TITLE
weird "operation cancelled"?

### ISSUE THREAD

**Issue by c-cube** [avsm/setup-ocaml#5]
not sure why https://github.com/c-cube/sqlite3_utils/runs/327596143 fails. Sorry to disturb you @avsm :sweat_smile:

**Comment by avsm** [comment]
This is because your build matrix is set to cancel outstanding jobs if any one of the matrix fails, which the Windows one did. See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast for more

**Comment by c-cube** [comment]
ahh, that makes sense. Thank you! :)
