### ISSUE TITLE
ubuntu: 404 on depext install

### ISSUE THREAD

**Issue by tjammer** [avsm/setup-ocaml#51]
I'm experiencing errors when installing packages on ubuntu (latest and 18.04):
```
The following command needs to be run through "sudo":
    apt-get install -qq -yy libasound2-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxi-dev libxrandr-dev m4 mesa-common-dev pkg-config xorg-dev
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/x/xorg-server/xserver-xorg-dev_1.19.6-1ubuntu4.7_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
OS package installation failed
Error: Process completed with exit code 1.
```
More details hre: https://github.com/tjammer/raylib-ocaml/runs/1506085611

It seems similar to this issue https://github.com/actions/virtual-environments/issues/2155 where they could fix it by running `apt-get update` before downloading.

Can this be fixed in my workflow file (https://github.com/tjammer/raylib-ocaml/blob/master/.github/workflows/main.yml) or in this Action?

**Comment by smorimoto** [comment]
I had just commented on that relevant commit. You need to run `sudo apt-get update` to temporarily avoid this problem, and this is not what we should do on the action side.

**Comment by tjammer** [comment]
This solved the problem. Many thanks for the quick help

**Comment by smorimoto** [comment]
Anytime :)
