### ISSUE TITLE
Question: docker

### ISSUE THREAD

**Issue by Kakadu** [avsm/setup-ocaml#64]
I'm have a deep knowledge in various CIs but it seems that `setup-ocaml` have issues with compilation speed (caching) and it should be possible to fix using custom docker image. Can yo mention in README either

1) using ocaml-setup + docker is not possible and some reasons about it 
2) how to use docker + ocaml-setup (or at least a link to a decent tutorial). I have issues with googling tutorial that I can understand. Although my intuition says that if using ocaml-setup+docker would be possible, you mentioned that in a README

**Comment by dra27** [comment]
As noted [in the readme](https://github.com/avsm/setup-ocaml#roadmap), features which benefit only one platform are avoided. GitHub Actions IIUC doesn’t use Docker for Windows and there’s no Docker for native macOS, so it’s not really a solution.

For Docker itself, there are already opam images (which achieve the same aim as this action) maintained and pushed to [ocaml/opam](https://hub.docker.com/r/ocaml/opam/tags) on Docker Hub.

See #1 for the main discussion on caching.

**Comment by Kakadu** [comment]
@dra27 To clarify: you don't know a way (or it doesn't exist) to use github-actions + docker to setup CI which will run on GNU/Linux for dune-based OCaml package?

**Comment by Kakadu** [comment]
Drup recommended to abandon the idea to speedup CI by using docker. Maybe I should follow his advice...
