### ISSUE TITLE
`opam install` on windows should not exit with code 0 when it fails to install the package

### ISSUE THREAD

**Issue by JasonGross** [avsm/setup-ocaml#72]
In https://github.com/mit-plv/fiat-crypto/pull/966/checks?check_run_id=2514865800#step:9:62, it says
```
Error:  The compilation of coq-fiat-crypto failed at "D:\\cygwin\\bin\\make.exe -j3 EXTERNAL_DEPENDENCIES=1 SKIP_BEDROCK2=1 coq-without-bedrock2 standalone-ocaml".
```
but then the overall step succeeds

**Comment by dra27** [comment]
This isn't setup-ocaml, it's GitHub Actions: the Unix shells run with `-e` but there's no equivalent for PowerShell or cmd (see [the docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell)).

The workflow you're running is:

```yaml
    - name: Install Fiat-Crypto
      run: |
        opam exec -- opam-depext coq-fiat-crypto
        opam install coq-fiat-crypto
        opam list
```

if you remove the `opam list`, it should behave as you expect (although I imagine you'd like to know about errors from opam-depext too)

**Comment by JasonGross** [comment]
Ah, thanks.  This is unfortunate
